### ISSUE TITLE
Empty File

### ISSUE THREAD

**Issue by rodrigo-sumar** [blefloch/latex-morewrites#13]
I upgraded to the latest version of the package, so I can use the write18 command to execute makeindex in several indices. However, each time the i run latex the files with the raw data of indices are created again. What causes makeindex to always find empty files.

**Comment by blefloch** [comment]
Can you send me a minimal example of code that shows the problem please?  Presumably some file is not closed in time but it is difficult for me to determine that without knowing what you are doing exactly.

**Comment by rodrigo-sumar** [comment]
In this example, i use the "index" package and create the command \indiceremissivo to redefine some index settings and automate makeindex.
  Every time i run latex the .idx file is rewritten and not updated. Then makeindex always read a  empty idx file.

Tanks,



\documentclass[oneside,       % para impressão somente na frente. Oposto a twoside
              openright,     % capítulos começam em pág ímpar (insere página vazia caso preciso)
               a4paper,       % tamanho do papel.
               12pt,          % tamanho da fonte
               english,		  % idioma adicional para hifenização
               french,		  % idioma adicional para hifenização%
               spanish,		  % idioma adicional para hifenização
               brazil		  % o último idioma é o principal do documento
               ]{memoir}

% ------
\usepackage[brazil]{babel}
\usepackage[latin1]{inputenc} % pacote para acentuacao direta
\usepackage{amsmath,amsfonts,amssymb,amsthm} % pacote matematico
\usepackage{graphicx} % pacote grafico
\usepackage[bottom]{footmisc}
\usepackage{subfig}
\usepackage{threeparttable}
\usepackage{index}
\usepackage{lipsum}				% para geração de dummy text
\DisemulatePackage{index}
% ---
\newcommand{\indiceremissivo}{
    \renewenvironment{theindex}{%% Formatação do índice
        \onecolumn
        \chapter*{\indexname}
        \preindexhook
      \indexmark
      \ifnoindexintoc\else
       \phantomsection
       \addcontentsline{toc}{chapter}{\MakeUppercase{\indexname}}{\indexname}%% Adição do índice ao sumário
      \fi
      \parskip\z@ \@plus 0.3\p@\relax
      \let\item\@idxitem
    }{%%
      \if@restonecol\onecolumn\else\twocolumn\fi
    }
     \immediate\write18{makeindex \jobname.idx -s estilo-indice.ist -o \jobname.ind}\relax
\IfFileExists{\jobname.ind}{
\cleardoublepage
\printindex
\cleardoublepage
}{Sua lista de termos s\'o vai aparecer aqui quando for rodar o makeindex.
Veja a documenta\c c\~ao para mais detalhes.}}
%%%%%%


\makeindex
\begin{document}
\listoftables
\tableofcontents%%%

%---------- Segundo Capitulo ----------
\chapter{Desenvolvimento}
\label{chap:desenv}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

A seguir ilustra-se a forma de incluir figuras, tabelas, equa\c{c}\~oes, siglas e s\'imbolos no documento, obtendo indexa\c{c}\~ao autom\'atica em suas respectivas listas. A numera\c{c}\~ao sequencial de figuras, tabelas e equa\c{c}\~oes ocorre de modo autom\'atico. Refer\^encias cruzadas s\~ao obtidas atrav\'es dos comandos {\ttfamily \textbackslash label\{\}} e {\ttfamily \textbackslash ref\{\}}. Por exemplo, n\~ao \'e necess\'ario saber que o n\'umero deste cap\'itulo \'e \ref{chap:desenv} para colocar o seu n\'umero no texto. Isto facilita muito a inser\c{c}\~ao, remo\c{c}\~ao ou reloca\c{c}\~ao de elementos numerados no texto (fato corriqueiro na escrita e corre\c{c}\~ao de um documento acad\^emico) sem a necessidade de renumer\'a-los todos.


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Tabela e Quadro: Diferenças}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\index{tabelas} As tabelas e os quadros facilitam a compreensão do fenômeno em estudo, uma vez que apresentam os dados de modo resumido, oferecendo uma visão geral do conteúdo em questão.

A tabela segue a norma NBR 14724:2011 subitem 5.9, que por sua vez, remete as Normas de Apresentação Tabular do Instituto Brasileiro de Geografia e Estatística - IBGE (1993). Já o quadro é citado no subitem 5.8 da NBR 14724:2011 como uma das categorias de ilustrações.

Basicamente, a diferença entre ambos está relacionada a formatação. A tabela apresenta os seguintes elementos: título, cabeçalho, conteúdo, fonte e, se necessário, nota(s) explicativa(s) (geral e/ou específica). É dividida por linhas na horizontal, porém as bordas  laterais não podem ser fechadas. Já o quadro, embora siga especificações semelhantes  (título, fonte, legenda, nota(s) e outras informações necessárias), terá suas  laterais  fechadas.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Tabelas}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Também são apresentados os exemplos das tabelas~\ref{tab:correlacao} e \ref{tab:cronograma}, que aparecem automaticamente na lista de tabelas. Informa\c{c}\~oes sobre a constru\c{c}\~ao de tabelas no \LaTeX\ podem ser encontradas na literatura especializada~\cite{Lamport1986,Buerger1989,Kopka2003,Mittelbach2004}.\\\vspace{12pt}


\begin{table}[!htb]
	\caption[Exemplo de uma tabela]{Exemplo de uma tabela mostrando a correla\c{c}\~ao entre x e y.}
	\label{tab:correlacao}
	\centering
	\begin{tabular}{cc}
		\hline
		x & y \\
		\hline
		1 & 2 \\
		3 & 4 \\
		5 & 6 \\
		7 & 8 \\
		\hline
	\end{tabular}
    \vspace{8pt} %%%% Deve ser acrescentado para que haja espaço entre o final da tabela e a fonte.
\end{table}


\begin{table}[!htb]
 \caption{Exemplo de cronograma usando \textit{bullet}}
 \label{tab:cronograma}
 \begin{center}
  \begin{tabular}{l||c|c|c|c|c|c|c|c}
    \hline
    \multicolumn{9}{c}{2003} \\ \hline \hline
    \multicolumn{1}{c||}{Fase} & Março     & Abril     & Maio     & Junho   & Julho & Agosto & Setembro & Outubro\\ \hline
    1    & $\bullet$ &           &          &         &  &  &  & \\
    2    &           & $\bullet$ & $\bullet$&         &  &  &  &\\
    3    &           &           & $\bullet$& $\bullet$ &  &  &  &\\
    4    &           &           &          &         &  $\bullet$& $\bullet$ &  &\\
    5    &           &           & & &  $\bullet$& $\bullet$ &  &\\
    6    &           &           & & &  &  &  $\bullet$&$\bullet$\\
    \hline
  \end{tabular}
 \vspace{8pt} %%%% Deve ser acrescentado para que haja espaço entre o final da tabela e a fonte.
 \end{center}
\end{table}


\indiceremissivo
\end{document}

**Comment by blefloch** [comment]
Thank you for the example document.  Sorry, I'm confused: it does not use the `morewrites` package and using the `morewrites` package does not seem to change the result at all.

It seems your specific problem is that the `idx` file is closed very late (at the very end of the TeX run) and `makeindex` runs before the file is closed (actually, even before anything is written to that file).
