### ISSUE TITLE
Conflict of latest morewrites package with nomenclature package

### ISSUE THREAD

**Issue by torstenelmkjaer** [blefloch/latex-morewrites#15]
The inclusion of the morewrites package in the example below lead to an empty .nlo nomenclature file:
```
\documentclass[10pt,a4paper,twoside,danish,english]{thesis}
\usepackage{morewrites}
\usepackage{nomencl}
\begin{document}
\makenomenclature     //
\printnomenclature    // the place where nomenclature is
\nomenclature{I}{Area moment of inertia}
\end{document}  
```

**Comment by blefloch** [comment]
Thanks for the report with code.  Unfortunately, I do not have the class file `thesis.cls`, probably local to your University.  Replacing `thesis` by `article` and using the last version of `morewrites` I correctly get a nomenclature (after running `makeindex` as per `nomencl`'s documentation).

The most likely issue is that you have an older version of `morewrites` (they had bugs).  Please get the latest version by

- downloading https://github.com/blefloch/latex-morewrites/archive/master.zip

- extracting `morewrites.ins`, `morewrites.dtx`, `primargs.dtx` from the zip

- running `pdflatex` on `morewrites.ins`

- copying the resulting `morewrites.sty` and `primargs.sty` somewhere TeX can find them, for instance the same directory as your main TeX file.

**Comment by torstenelmkjaer** [comment]
Hi Bruno,

Thanks for the reply.
I took sometime of in order to reinvestigate the ”case”.

Using the following short example now with the report class

\documentclass[10pt,a4paper,twoside,danish,english]{report}
\usepackage{nomencl}
\usepackage{morewrites}
\begin{document}
\makenomenclature     //
\printnomenclature    // the place where nomenclature is
\nomenclature{I}{Area moment of inertia}
\end{document}

And with

[cid:image001.png@01D2D738.4903C550]

However, did still lead to an empty nomenclature file:

[cid:image003.png@01D2D738.4903C550]



I have used these two packages over the last 10 years without any problems hitherto.
Any help will be greatly appreciated – thanks!

B.R.
Torsten Elmkjær


Fra: Bruno Le Floch [mailto:notifications@github.com]
Sendt: 12. maj 2017 03:18
Til: blefloch/latex-morewrites <latex-morewrites@noreply.github.com>
Cc: Torsten Haber Leth Elmkjær <thle@ms3e.dk>; Author <author@noreply.github.com>
Emne: Re: [blefloch/latex-morewrites] Conflict of latest morewrites package with nomenclature package (#15)


Thanks for the report with code. Unfortunately, I do not have the class file thesis.cls, probably local to your University. Replacing thesis by article and using the last version of morewrites I correctly get a nomenclature (after running makeindex as per nomencl's documentation).

The most likely issue is that you have an older version of morewrites (they had bugs). Please get the latest version by

  *   downloading https://github.com/blefloch/latex-morewrites/archive/master.zip
  *   extracting morewrites.ins, morewrites.dtx, primargs.dtx from the zip
  *   running pdflatex on morewrites.ins
  *   copying the resulting morewrites.sty and primargs.sty somewhere TeX can find them, for instance the same directory as your main TeX file.

**Comment by flueterflam** [comment]
I tried building the MWE provided and did not have any problems with `morewrites` and `nomencl`.  Should this issue be closed (because there has not been any follow-up since May 2017 anyway)?

I speculate there was another factor in this problem - but without the environment and exact compilation steps, it is difficult to say.

**Comment by blefloch** [comment]
Indeed, I tried a few combinations of versions without being able to reproduce the bug, sorry.
