### ISSUE TITLE
! I can't write on file `main.mw'.

### ISSUE THREAD

**Issue by xexeo** [blefloch/latex-morewrites#17]
I am using morewrites in a  book project with many packages in MiKTeX and using pdfLaTeX, since there was no more writes available.

I am getting the error: ! I can't write on file `main.mw'

or even ! I can't write on file `main.mw.mw.mw.mw'.

It seems that I am not able to generate a minimum example, since it seems to be connected with the fact of my project being large. I can however send you a rar file of all the project with about 80Mb.

Just to make things tougher, sometimes it works...

Here is the end of the log:
\openout3 = `main.mw.mw.mw.mw.mw'.

[167] (main.mw.mw.mw.mw.mw)
! I can't write on file `main.mw.mw.mw.mw.mw'.
<to be read again> 
                   \scan_stop: 
l.211 

       
Please type another output file name
! Emergency stop.
<to be read again> 
                   \scan_stop: 
l.211 

       
*** (job aborted, file error in nonstop mode)

 
Here is how much of TeX's memory you used:
 69181 strings out of 492449
 1580137 string characters out of 3129732
 2334628 words of memory out of 3000000
 70757 multiletter control sequences out of 15000+200000
 651966 words of font info for 198 fonts, out of 3000000 for 9000
 1141 hyphenation exceptions out of 8191
 67i,18n,114p,10129b,3396s stack positions out of 5000i,500n,10000p,200000b,50000s
!  ==> Fatal error occurred, no output PDF file produced!

**Comment by blefloch** [comment]
I'm pretty busy in real life at the moment so I can't promise anything.

Can you check main.mw, main.mw.mw, etc don't contain useful data (e.g.,
check that you don't have a Maple worksheet called main.mw) and delete
them all, then try again?

Can you tell me what version of morewrites you are using?  It should
appear somewhere near the start of the log file as something like

Package: morewrites [date] [version] [text]

**Comment by blefloch** [comment]
Without further reaction, I'm closing this.
